### ISSUE TITLE
add q=category for list of tags

### ISSUE THREAD

**Issue by swentel** [swentel/indieweb#167]
See https://github.com/swentel/indigenous-android/issues/33

**Comment by dshanske** [comment]
https://indieweb.org/Micropub-extensions mentions it. The other place for experimental property discussion is https://indieweb.org/Micropub-brainstorming If you implement it, servers will too.

**Comment by dshanske** [comment]
Currently, to my knowledge, only the WordPress server supports it.

**Comment by swentel** [comment]
Ok this is in on the drupal side! Now to the Android client :)
