### ISSUE TITLE
What is bridg.y?

### ISSUE THREAD

**Issue by eelkeblok** [swentel/indieweb#226]
The readme says: “Publish content, likes etc via bridg.y, store syndications”. What is bridg.y? I tried googling and searching in the repo, but the only hit is that line in the readme. I suspect it's a typo, but of what?

**Comment by swentel** [comment]
Oh my yes, that should by brid.gy :)

**Comment by eelkeblok** [comment]
:) Cool. Well, have a PR then :) #227.

**Comment by swentel** [comment]
Awesome, thanks, getting back after holiday, I'll get this in somewhere this week.
I'll also add your username to the git commit on d.o - https://www.drupal.org/u/eelkeblok right ?

**Comment by eelkeblok** [comment]
Yes. Cheers!

**Comment by swentel** [comment]
merged, thanks!
