### ISSUE TITLE
Allow module to act in the fediverse

### ISSUE THREAD

**Issue by swentel** [swentel/indieweb#246]
This would be freaking awesome, but hard :)
Bridgy Fed is still the main service here to use of course.

What we need (not a full list yet)

- .webfinger : authentication (https://github.com/snarfed/bridgy-fed/blob/master/webfinger.py)
- activitypub: inbox, outbox to send or receive posts
- content negotiation for actor/discovery/streams e.g. https://fed.brid.gy/realize.be

Library we can use: https://github.com/landrok/activitypub

Question is: maybe this should be a complete separate module and not live in the indieweb module at all. Although indieweb_activitypub would work for me if we can use the library above since we probably don't need that many glue code, and we have services we can use 

- to create a comment (WebmentionClient::createComment() - although we'd have to rework that a bit, or we can treat incoming stuff from AP as webmentions)
- notify in microsub

I also need a migration path from fed.brid.gy since it controls my realize.be account now (@realize.be@realize.be on mastodon for instance) , but that's not necessary for this module, only something I need to talk with snarfed about.

**Comment by axel-rutz** [comment]
Can you explain what this means and what is missing?

**Comment by swentel** [comment]
Updated the original summary a bit, but probably misses things. The library I mentioned seems pretty useful nowadays (the first time I looked at it, it was very basic).

This is tricky stuff (AP leaves many things open to implementers, which is annoying). Mastodon is the only one we know right now which works fine with fed.brid.gy. Figuring out how other services implement AP is tricky since you need to look at the code.

**Comment by axel-rutz** [comment]
THX! Now i get a glimpse of an image...

**Comment by swentel** [comment]
Going to develop this in a separate module, see https://github.com/swentel/activitypub :)
(code coming soon)
