### ISSUE TITLE
Get more user info when authenticating

### ISSUE THREAD

**Issue by swentel** [swentel/indieweb#249]
e.g. the user h-card so we can set picture, name etc
optionally also e-mail, but this is also related to #206

**Comment by swentel** [comment]
Actually going to leave this as is, sites should set it with fields if they want to.

**Comment by swentel** [comment]
otoh, this is cool :)
not necessary for release 1.0 though

**Comment by axel-rutz** [comment]
At hubs4change we are very interested in this too. Also very interested in exposing "my organisation(s)" for our use cases. (I've just started to grok stuff here s

**Comment by swentel** [comment]
I've added a hook for this: hook_indieweb_indieauth_login($account, $indieauth_response);
This makes it easier to act on the account when registering or logging in.
