### ISSUE TITLE
Codestyle a bit of PHP4

### ISSUE THREAD

**Issue by jepster** [swentel/indieweb#332]
Hi, firstly thanks a lot for your module! I have checked the code of MicropubController. The postEndpoint() method seem way too long. I would suggest to split methods for maintainability. There can go wrong more, if you have such a procedural method. What do you think?

**Comment by jepster** [comment]
Thanks for your quick answer @swentel. Yep, most important is, that the stuff is covered. To be honest it's also a bit odd to split things in methods, which are probably used only once. I will play around more with your module and share my findings.

**Comment by swentel** [comment]
Closing this one to clean the queue a bit. Feel free to open PR to clean up code if you want :)
