### ISSUE TITLE
Status code 403 when trying to post an note

### ISSUE THREAD

**Issue by jepster** [swentel/indieweb#334]
This is a support request.

After defining the RelMeAuth tag for GitHub on my site, I was able to sign in via IndieAuth. Then I tried to post a "Note" to my site via Indigenious Android app. I could not, since the app shown me a 403 HTTP status code (The HTTP 403 Forbidden client error status response code indicates that the server understood the request but refuses to authorize it.).

However, this seems correct to me, since only authorized people should be able to post to my site. In Indigenious app I have just entered my domain and that (obviously) should not be enough for posting to my site.

Two questions:
- Which setting do I need to specify for being able to post to my site via the Indigenious Android app? 
- I would also like to post to my site and to Twitter at once. Is this possible or has Twitter shut doors here?

**Comment by swentel** [comment]
Hmm, that's interesting. Since Indigenous can authenticate, it should have received an access token form indieauth.com. That access token is send to your micropub endpoint, and this token is validated then at indieauth.com with a server request. There is no error message in the watchdog when trying to post ? (e.g. something like 'indieweb_scope' or 'indieweb_token' ?)

Regarding 2: for this I am using https://brid.gy/. At 'admin/config/services/indieweb/send' you can configure the syndication targets, but it probably contains twitter already. You authenticated at brid.gy for api access, which should only take a few seconds. After that, the last thing to configure is to make sure that the 'Twitter' field is rendered on the canonical url of the post, including the right microformats too.

**Comment by jepster** [comment]
That's the only watchdog error I am retrieving:

> Warning: file_get_contents(): Filename cannot be empty in Drupal\indieweb_indieauth\IndieAuthClient\IndieAuthClient->validateTokenInternal() (line 164 of /var/www/mobilefish.de/modules/contrib/indieweb/modules/indieweb_indieauth/src/IndieAuthClient/IndieAuthClient.php) #0 /var/www/mobilefish.de/core/includes/bootstrap.inc(584): _drupal_error_handler_real(2, 'file_get_conten...', '/var/www/mobile...', 164, Array) #1 [internal function]: _drupal_error_handler(2, 'file_get_conten...', '/var/www/mobile...', 164, Array) #2 /var/www/mobilefish.de/modules/contrib/indieweb/modules/indieweb_indieauth/src/IndieAuthClient/IndieAuthClient.php(164): file_get_contents('') #3 /var/www/mobilefish.de/modules/contrib/indieweb/modules/indieweb_indieauth/src/IndieAuthClient/IndieAuthClient.php(38): Drupal\indieweb_indieauth\IndieAuthClient\IndieAuthClient->validateTokenInternal('Bearer eyJ0eXAi...', 'create') #4 /var/www/mobilefish.de/modules/contrib/indieweb/modules/indieweb_micropub/src/Controller/MicropubController.php(372): Drupal\indieweb_indieauth\IndieAuthClient\IndieAuthClient->isValidToken('Bearer eyJ0eXAi...', 'create') #5 [internal function]: Drupal\indieweb_micropub\Controller\MicropubController->postEndpoint(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/mobilefish.de/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #7 /var/www/mobilefish.de/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #8 /var/www/mobilefish.de/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #9 /var/www/mobilefish.de/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #10 /var/www/mobilefish.de/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #11 /var/www/mobilefish.de/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #12 /var/www/mobilefish.de/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/www/mobilefish.de/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #14 /var/www/mobilefish.de/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #15 /var/www/mobilefish.de/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #16 /var/www/mobilefish.de/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /var/www/mobilefish.de/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /var/www/mobilefish.de/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /var/www/mobilefish.de/core/lib/Drupal/Core/DrupalKernel.php(669): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /var/www/mobilefish.de/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #21 {main}.

I have not configured any "Tokens" and "Authorization codes".

![screenshot_20181125-175137](https://user-images.githubusercontent.com/628434/48981872-33102400-f0db-11e8-81b4-00a9424b75a4.jpg)

Here are my settings for the note content type:
![note](https://user-images.githubusercontent.com/628434/48981901-897d6280-f0db-11e8-8d45-89dd71078c48.png)

Here are my settings for indieauth:
![indieauth-settings1](https://user-images.githubusercontent.com/628434/48981907-95692480-f0db-11e8-8a14-eedd1536b98e.png)
![indieauth-settings2](https://user-images.githubusercontent.com/628434/48981911-99954200-f0db-11e8-9f56-b79364a4f53e.png)

**Comment by jepster** [comment]
If I need any tokens, how can I configure them? I do not see any "add token" functionality.

**Comment by swentel** [comment]
Oh I see. For the internal endpoint, you need to generate keys. There's a little checkbox 'generate keys on save' you can toggle to generate a public and private key which is used to generate JWT tokens. Ideally, you can set the path outside the webroot as that's safer of course. In settings.php you can override that path, as the default is public://indieauth. 

```
$settings['indieauth_keys_path'] = '/your/path/';
```

Once that's set, you will have to re-authenticate in indigenous: basically, delete the account, start over to get a new access token there (that flow is obviously something I need to fix for the app)

**Comment by jepster** [comment]
Unfortunately I still cannot post. What did I?

1. Modified my settings.local.php file and added this line: 
`$settings['indieauth_keys_path'] = '/PATH/TO/DOCROOT/sites/default/indieauth_keys/';`
2. In that folder my indieauth keys are located, which I have created like desribed in the README.md in the Indieweb Drupal module file:

> user@computer:/DOCROOT/sites/default/indieauth_keys# ls -la
> total 16
> drwxr-xr-x 2 root root 4096 Nov 25 18:14 .
> drwxrwxrwx 4 1000 1000 4096 Nov 25 18:27 ..
> -rw------- 1 root root 1679 Nov 25 15:32 private.key
> -rw------- 1 root root  451 Nov 25 15:32 public.key
> 

3. Uninstalled the Indigenious Android app and installed it again. Then I have added my site again to the app. 
4. Tried to add an note content and got still the error message.

Do you have any further idea? Regarding the setup flow: May a multi-step form (done via the Drupal API) would help here some users.

**Comment by jepster** [comment]
P.S: The paths in the keys settings form are not overriden via the config of my settings.local.php file:
![schnappschuss_112518_063414_pm](https://user-images.githubusercontent.com/628434/48982291-c9931400-f0e0-11e8-84f5-e0a55ab5eab3.jpg)

**Comment by swentel** [comment]
Hmm, in my case, the public key path is set to ```/home/swentel/swentel-private/keys/public.key```
However, I noticed I created them by toggling the 'generating keys' checkbox and it wrote it to my 'private file system' which is set to  /home/swentel/swentel-private

```
$settings['file_private_path'] = '/home/swentel/swentel-private';
```

So, I think you can just set the full path there in those two textfields. My guess is the post generated an error again as it can't find the public key, and generating one probably triggered one as well.

(and yes, the UX here needs to be fixed, I just committed this today, so that needs work :)

**Comment by jepster** [comment]
I have removed the line from my settings.local.php file, re-created the IndieAuth keys to check if it's working at all (without moving the keys into any home folder directory). I have re-installed the Indigenious app on my phone. The result was still the same. There is no error appearing in my watchdog. It seems there is any bug. I have no idea.

**Comment by jepster** [comment]
Tried to post with quill. It give a bit more information. However, still nothing what would point me to the right direction:
![schnappschuss_112518_065714_pm](https://user-images.githubusercontent.com/628434/48982522-07456c00-f0e4-11e8-89c7-8dabe1729166.jpg)

**Comment by swentel** [comment]
Do you see a token at 'admin/config/services/indieweb/indieauth/tokens' ?
Or maybe a left over token at 'admin/config/services/indieweb/indieauth/authorization-codes' ?

**Comment by swentel** [comment]
Ok, I think I see one last potential problem: the endpoints on mobilefish.de are still set to indieauth.com, they should be pointing to the internal endpoints. You now have this

```
<link rel="authorization_endpoint" href="https://indieauth.com/auth" />
<link rel="token_endpoint" href="https://tokens.indieauth.com/token" />
```

but that should be something like

```
<link rel="authorization_endpoint" href="https://mobilefish.de/indieauth/auth" />
<link rel="token_endpoint" href="https://mobilefish.de/indieauth/token" />
```

**Comment by swentel** [comment]
Interesting, they are now ok, I'm starting to wonder whether I'm seeing ghosts now :)

**Comment by jepster** [comment]
I must have overlooked something. The setting fields for the private and public key where empty. Then I have re-genereted them (just via checkbox, without modifying the path). Afterwards I tried to send a note via the app. Then I got the error 
![screenshot_20181125-192930](https://user-images.githubusercontent.com/628434/48982898-863ca380-f0e8-11e8-8b86-31288c5c4256.jpg)

**Comment by jepster** [comment]
That's what watchdog is showing me for this request:
![schnappschuss_112518_073114_pm](https://user-images.githubusercontent.com/628434/48982913-b4ba7e80-f0e8-11e8-8d47-d1f81689481a.jpg)

**Comment by jepster** [comment]
Ah, the settings for the note content type where disabled. Must happened during my config reset. Now the note content have been created. :)

But... the content cannot be edited:
![schnappschuss_112518_073334_pm](https://user-images.githubusercontent.com/628434/48982934-006d2800-f0e9-11e8-967e-60cba393ff76.jpg)
When I click the edit button, I get this error:
![schnappschuss_112518_073418_pm](https://user-images.githubusercontent.com/628434/48982939-1a0e6f80-f0e9-11e8-94a8-88759c46bcd4.jpg)

**Comment by jepster** [comment]
Ah.. I had no content type configured in the indieweb settings. Well, now I need to delete a "garbage node" via database.

**Comment by swentel** [comment]
> Ah.. I had no content type configured in the indieweb settings. Well, now I need to delete a "garbage node" via database

Oh, the note didn't have a drupal content type configured anymore ? In that case, yes, we should add exception handling there - it's interesting that drupal doesn't even crash on that by default

**Comment by swentel** [comment]
I just found an extremly stupid problem with the settings form. See #336 - this is why manually editing that form didn't work :/

**Comment by jepster** [comment]
Thank you so much Kristof for your blazing fast support and the work on Indieweb. The Indieweb concept is amazing!
