### ISSUE TITLE
Posting to Twitter

### ISSUE THREAD

**Issue by jepster** [swentel/indieweb#342]
You wrote me in the issue at https://github.com/swentel/indieweb/issues/334 the following message about enabling Twitter support: 

> Regarding 2: for this I am using https://brid.gy/. At 'admin/config/services/indieweb/send' you can configure the syndication targets, but it probably contains twitter already. You authenticated at brid.gy for api access, which should only take a few seconds. After that, the last thing to configure is to make sure that the 'Twitter' field is rendered on the canonical url of the post, including the right microformats too.

I have enabled the "Webmention" module. There is a syndication target already configured:

> Twitter (bridgy)|https://brid.gy/publish/twitter

I have also set 

> SENDING WEBMENTIONS
> On cron run

In the micropub settings I have configured the note content type. If I execute the cron run, my indieweb post is not being posted to Twitter by my Drupal instance.

Could you please describe me a step-by-step instruction for the settings, which are needed to configure Twitter posting?

**Comment by swentel** [comment]
You have to go to https://brid.gy/ and connect your twitter account. Basically, it uses the API of twitter to publish on your behalf and read your timeline for the backfeed.

When you post something make sure the link to bridgy (publish/twitter) is rendered on that page. You can configure that on the manage display pages and the right microformats are rendered too. You can test in brid.gy itself by letting it analyze a page. Also, either you expose a microformats feed (via the feeds module) which bridgy uses so it knows the original post, or your let brid.gy publish a tweet with the original url, but that's less 'pretty'.

You can always host brid.gy yourself, or even implement those api's yourself, but that's a bit of work :)
