### ISSUE TITLE
Error while trying to add a Source under Microsub

### ISSUE THREAD

**Issue by sparxsys** [swentel/indieweb#352]
Error description below, copied from the Drupal log.

Drupal\Core\Entity\EntityStorageException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'items_to_keep' in 'field list': INSERT INTO {microsub_source} (uuid, url, uid, status, channel_id, post_context, hash, fetch_interval, fetch_next, fetch_tries, cache_image_disable, items_in_feed, items_to_keep) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12); Array ( [:db_insert_placeholder_0] => 6df3a514-420d-4f5c-bc7f-b022695ac139 [:db_insert_placeholder_1] => https://www.instagram.com/ravisagar.in/ [:db_insert_placeholder_2] => 1 [:db_insert_placeholder_3] => 1 [:db_insert_placeholder_4] => 2 [:db_insert_placeholder_5] => a:4:{s:5:"reply";s:5:"reply";s:8:"bookmark";s:8:"bookmark";s:4:"like";i:0;s:6:"repost";i:0;} [:db_insert_placeholder_6] => [:db_insert_placeholder_7] => 3600 [:db_insert_placeholder_8] => 0 [:db_insert_placeholder_9] => 0 [:db_insert_placeholder_10] => 0 [:db_insert_placeholder_11] => 0 [:db_insert_placeholder_12] => 0 ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 783 of /path/apps_ravisagar/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

**Comment by swentel** [comment]
This is a new field that was added between 8.x-1.0-beta7 and 8.x-1.0-rc1, there are two ways around this:

- either run 'drush entup'
- or uninstall, then reinstall the module
