### ISSUE TITLE
Add more microformats to micropub

### ISSUE THREAD

**Issue by geek-merlin** [swentel/indieweb#366]
What we will need soon is

* [h\-geo](http://microformats.org/wiki/microformats2#h-geo)
* [h\-org](http://microformats.org/wiki/microformats2#h-card_org_h-card)
* [h\-product
](http://microformats.org/wiki/microformats2#h-product)

**Comment by axel-rutz** [comment]
Not only for micropub...

**Comment by swentel** [comment]
Relates a bit with #171

**Comment by swentel** [comment]
Closing this for now. I don't have a specific need for it right now. If you have patches, always welcome of course :)
