### ISSUE TITLE
How can i pull remote content?

### ISSUE THREAD

**Issue by axel-rutz** [swentel/indieweb#367]
Background: With the Drutopia-based Hubs4Change Distro, we want to provide regional hubs with a tool to create maps of sustainability-pioneers (companies and initiatives), events, articles. We want all the content to be federated (read: mirrored) between sites.

Currently i don't grok how i can pull / scrape content from another federated site?  Naively i think of "Add some remote site urls and stuff will be [pulled](https://indieweb.org/h-feed#How_to_consume) from there.

It does look like this is not a supported use case yet. Is another federation use case supported? Any ideas or prior art on this?

**Comment by axel-rutz** [comment]
Oh, i found microsub sources, interesting...

**Comment by swentel** [comment]
What's the goal. Mirror exact content between sites ? If so, that's not immediately a use case IndieWeb or Federated platforms try to solve. Although you can of course use microsub items to store feeds from other sites and then somehow display them. The module itself does not have a way to display that content on the site though, it's for indieweb readers only at the moment, but nothing stops us of course to add something like this :)

**Comment by swentel** [comment]
Closing this for now. See previous comment, it's not the goal to do exact mirroring of content between sites. There are other tools for that in the Drupal universe.
