### ISSUE TITLE
"comment_body" field is assumed during webmention -> comment transform

### ISSUE THREAD

**Issue by sonniesedge** [swentel/indieweb#396]
Following from #389, I now find that the main text of a reply is not being inserted into a newly created comment.

Trying to debug this I noticed that my comment body field is called `field_body` and not the `comment_body` that Indieweb is searching for.

This difference is because I (quite foolishly) installed Drupal using the minimal installation profile. When I realised that this is a bad idea, I recreated the comment types and fields manually.

Because a manually created comment field has the prefix `field_` there is no way the comment body field can be recreated in the way Indieweb expects. (at least, not via the UI - I will explore using the core standard install profiles to fix this).

I'm not expecting everything to be altered to accommodate what I assume is an edge case. But I though it was best to record it!

**Comment by swentel** [comment]
Hmm I'm away from keyboard, but if I remember correctly, you don't need a body field, but an entity reference field.

Could be wrong of course, but wanted to let you know that already before you start deleting fields :)

**Comment by sonniesedge** [comment]
No worries, and thanks for the quick afk reply. Will play on a local copy before I touch the real site. ;)

**Comment by swentel** [comment]
Double checked this again. There are some hard coded places in some parts of the modules which rely on the comment body being called 'comment_body'. Normally, if you create a new comment type, Drupal will automatically add a body field with and the machine name should be 'comment_body'. (happens in CommentManager::addBodyField() of the comment module).

When it comes to creating a comment from a webmention, I don't search for a body field. What's needed on the comment type is an entity reference field. The indieweb module comes with a default storage field, so on the comment type screen, in the 'Re-use an existing field' drop down, you can select the indieweb_webmention field. In the end you should end end up with at least two fields on the comment type, being comment body and the webmention field, see screenshot. The screenshot also includes a link field which can store a link to a reply (you can reply on an incoming comment and then directly send it to bridgy for instance so it gets in the right thread).

![manage-fields](https://user-images.githubusercontent.com/168466/54074704-05b84200-4296-11e9-99b5-018221807ca3.png)

When a webmention comes in and a comment should be created, the webmention id is stored in that field. The actual content/reply of the webmention still lives in the webmention itself. To display it on the site, you need to add it on the manage display screen then, see screenshot.

![manage-display](https://user-images.githubusercontent.com/168466/54074719-34ceb380-4296-11e9-814e-bc03726fdbd4.png)

Notice also that I have the microformats display mode enable as well. That one will also display the link in case it's a reply, so when you would send a webmention to another site or bridgy, when it's processed, it ends up on all the right places.

Hope it helps! :)

**Comment by sonniesedge** [comment]
Thank you for taking the time to write that extremely helpful info! Following all that I believe I now have the comments set up correctly (btw, I found that simply uninstalling and reinstalling the core Comment module was the easiest way to solve the comment body name problem).

However, very frustratingly, #389 has started to show up again, with the same error, even when using the fix that previously worked. 😞

**Comment by swentel** [comment]
Hmm, weird. Can you give me an example of a webmention that fails to create a comment ? Most of my replies come from twitter, but shouldn't matter that much I think. If it's a reply from twitter, it would be handy to have the source url as well, usually a long url that starts with https://brid-gy.appspot.com.

**Comment by sonniesedge** [comment]
So, I've just tried reprocessing an `in-reply-to` that I already had on a piece of content.

**Original content:** 
https://www.sonniesedge.net/notes/2121

**Bridgy source URL:** 
https://brid-gy.appspot.com/comment/twitter/sonniesedge/1100486642941526016/1100510076740218881 

**Run via:**
`drush @live indieweb:process-webmentions -l https://www.sonniesedge.net`

**Error:**
`[notice] Failed to create a comment: The internal path component 'https://www.sonniesedge.net/notes/2121' is invalid. Its path component must have a leading slash, e.g. internal:/foo.`

**Comment by swentel** [comment]
Hmm, this is weird, when I run the code that should replace the hostname from the url, it comes back  fine as /notes/2121. So a bit in the dark at the moment. This might be https://github.com/swentel/indieweb/issues/85 coming back at me now - to be fair, it's totally deserved :)

However, not giving up, could you try the following:

1. open modules/indieweb/modules/indieweb_webmention/src/Commands/WebmentionCommands.php
2. paste following code inside the processWebmentions() method, above the if statement.
```
$hostname = \Drupal::request()->getSchemeAndHttpHost();
    drush_print("Hostname is " . $hostname);
    $target = 'https://www.sonniesedge.net/notes/2121';
    drush_print("Target to remove hostname from: $target");
    $target = trim(str_replace(\Drupal::request()->getSchemeAndHttpHost(), '', $target));
    drush_print("After str_replace, target is now " . $target);
    return;
```
3. run that command again :)

I'm curious about the output there.

**Comment by sonniesedge** [comment]
Did a very naughty bit of live editing files on my server. 😂

The result (after setting the `in-reply-to` to reprocess) is:
```
Hostname is https://sonniesedge.net
Target to remove hostname from: https://www.sonniesedge.net/notes/2121
After str_replace, target is now https://www.sonniesedge.net/notes/2121
```

**Comment by sonniesedge** [comment]
oh my god I just found the issue:
In my self.site.yml file `live` URL alias set as 

```
uri: https://sonniesedge.net`
```

instead of:

```
uri: https://www.sonniesedge.net
```
Changing it over fixed everything.

The reason why it didn't show up as an issue before is because I was SSHing directly into my server and running the drush indieweb commands there.

I am SO sorry for wasting your valuable time on this one!

**Comment by swentel** [comment]
Oh my, I would have never thought about that one :)

I've reopened #85 to refactor this out. It shouldn't fail here anyway as I really don't care about the hostname, just the target.
