### ISSUE TITLE
Support request: why does bridgy create imcomplete URLs for backlinks (on twitter)?

### ISSUE THREAD

**Issue by yoroy** [swentel/indieweb#411]
Hey, had to go way back and get yoroy.com proporly composerized, now working through setting up indieweb again. I'm running into this:

Example: https://twitter.com/royscholten/status/1126834942816788480

the backlink is "/node/bla" instead of "yoroy.com/node/bla". I can't find out where/how that part is left out. Any pointers? Thanks :)

**Comment by swentel** [comment]
I've seen them too, but couldn't come up with something yet. Using http://xray.p3k.io/parse?url=https%3A%2F%2Fyoroy.com%2F443&pretty=true it looks like everything seems ok to me.

So pinging @snarfed to see if he has an idea (it's probably going to be something stupid hehe)

**Comment by snarfed** [comment]
sorry for the trouble, guys!

@yoroy, your site includes rel-canonical and rel-shortlink links which bridgy publish obeys when it includes the backlink to your post(s): https://brid.gy/about#short-link

```
<link rel="canonical" href="/443" />
<link rel="shortlink" href="/node/443" />
<link rel="revision" href="/443" />
```

looks like bridgy should be expanding those into full URLs, but isn't. sounds like a bug. thanks for reporting!

**Comment by swentel** [comment]
@snarfed oh interesting. These are standard rel links that Drupal generates. I should be able to alter in to return full urls including the domain, but maybe that's overhead anyway.

(I don't have that problem currently since my frontend is in vue.js, Drupal is the backend)

**Comment by swentel** [comment]
If that's going to be fixed on your end though, then I close this.
(I can imagine other sites might do the same)
