### ISSUE TITLE
Syndications exposed via JSONAPI return 500 internal error

### ISSUE THREAD

**Issue by sonniesedge** [swentel/indieweb#416]
When using the JSON:API interface syndications return a 500 error.

```
detail: "Parameter \"entity\" for route \"jsonapi.indieweb_syndication--indieweb_syndication.individual\" must match \"[^/]++\" (\"\" given) to generate a corresponding URL."
```

## Example
https://cms.sonniesedge.net/jsonapi/indieweb_syndication/indieweb_syndication

**Comment by swentel** [comment]
Fixed, see commit - or use the next dev built of course :)

**Comment by swentel** [comment]
Hmm, this broke all tests, seriously :) Checking now.

**Comment by swentel** [comment]
Ok, the actual fix is different, but I need to write an update hook for it. Checking if I can do it differently.

**Comment by sonniesedge** [comment]
Thanks for looking into this - really appreciate the time and effort! ❤️

**Comment by swentel** [comment]
fixed - there's no new release yet, but the dev built is fine.
When updating, run drush updb (or update.php in the browser), this installs the  uuid field and generates uuid values for old syndications.

**Comment by sonniesedge** [comment]
Amazing! Thank you! 🎉 ❤️ 😁
