### ISSUE TITLE
Indieweb admin permissions required to view syndications 

### ISSUE THREAD

**Issue by sonniesedge** [swentel/indieweb#417]
"The current user is not allowed to GET the selected resource. The 'administer webmention entities' permission is required."

This is a high permission threshold for something read only. It makes the JSON:API impossible to use without logging in with a suitably permission-blessed account. 

There should more ideally be a granular "View syndications" permission?

**Comment by swentel** [comment]
Hmm yeah,  that's a bit too much. I have declared a 'view indieweb syndications' permission, but it's not used anymore, weird :)

I'll add a new admin permission,  something  like 'administer syndications' to use for administration actions, and use the other one for viewing.

**Comment by swentel** [comment]
Quick question: is this for the list of  syndications, of  individual, or  both?

**Comment by swentel** [comment]
nevermind I see collection  has the problem too

**Comment by swentel** [comment]
ok fixed - you can toggle the 'View syndications' for anonymous users now :)
(use the dev build, no new release yet)
