### ISSUE TITLE
'Expose authentication API link tag' results in error

### ISSUE THREAD

**Issue by aleksip** [swentel/indieweb#420]
Ticking the 'Expose authentication API link tag' checkbox in IndieAuth settings results in an error: `Symfony\Component\Routing\Exception\RouteNotFoundException: Route "indieweb.indieauth.auth_endpoint" does not exist.`

**Comment by swentel** [comment]
Wow, what a stupid bug :)
Committed and pushed, also a new release on d.o

**Comment by aleksip** [comment]
Thanks @swentel!
