### ISSUE TITLE
Support dt-published and dt-updated in received webmentions

### ISSUE THREAD

**Issue by aleksip** [swentel/indieweb#422]
Have just managed to get this amazing set of modules working, and my site can now receive webmentions from Bridgy. Now I would like to use Bridgy's retry option to get webmentions for my old blog posts.

Trying this, it seems that Twitter retweets get the correct `created` date from a Bridgy retry but 'likes' do not (this could also be a Bridgy bug or just impossible to do?).

It seems that webmentions are  currently ordered by id. Would be great to be able to order them by `created`/`changed` or `dt-published`/`dt-updated`. Are `dt-published` and `dt-updated` supported in received webmentions (https://brid.gy/about#order)? Could not find any related code in the webmention module.

I could have a go at this. Would `dt-published` and `dt-updated` require a schema change, or should they just be used for `created` and `changed`? What do you use for sending test webmentions when developing the module?

**Comment by swentel** [comment]
dt-published and dt-updated, if available can be mapped to created and changed, that seems logical. 

However, Bridgy doesn't have timestamps for likes - you can always look at the source of a bridgy url to verify (note, it does a meta refresh - so better fetch it with curl)

> It seems that webmentions are currently ordered by id

You mean, the webmentions that are displayed with the block - WebmentionBlock? That's ordered by id indeed (in WebmentionStorage::getWebmentions()). It's possible to use views normally too (although I've never tested it)

**Comment by aleksip** [comment]
> dt-published and dt-updated, if available can be mapped to created and changed

Ok, changed the issue title to focus on this.

> Bridgy doesn't have timestamps for likes

Do you know why?

> It's possible to use views normally too (although I've never tested it)

Ah, of course! Tried this, but came across a new problem. Opening a new issue for that.

**Comment by swentel** [comment]
My guess is that twitter itself doesn't log the timestamp for likes, or doesn't expose it in the API. Best guess though :)

**Comment by swentel** [comment]
So I checked in WebmentionClient::processWebmentions().

The parsing is done by xray, which uses the mf2 library to get the data. dt-published is fetched (if available) and then inside processWebmentions() this is used to set the created time. So that one was already covered.

Added a line for updated, so that's fine now too.

**Comment by aleksip** [comment]
Great, thanks!
