### ISSUE TITLE
Problems with trying to create webmention views

### ISSUE THREAD

**Issue by aleksip** [swentel/indieweb#423]
I'm trying to create webmention views so I could order webmentions by `created` and also have a block for webmentions with the property `mention-of` (retweet with comments in Twitter) since they do not seem to show up in either comments or the Webmentions block(?).

The main problem is that when I add a Property filter criteria, and add one or more from the list, saving the filter results in an error message: `No valid values found on filter: Webmention: Property.`

Additional challenge: creating a contextual filter based on the URL alias for the webmention target, not sure if this can be done using core views UI?

Also it seems that the `webmention.html.twig` template is not used in a view when rendered as a Webmention with the only available Default view mode?

**Comment by swentel** [comment]
So ironically I have no immediate answers as the frontend of my site is in Vue.js and I have custom endpoints to get the data. I'm redesigning my site however, so I'll get to this problem as well quite soon, probably in a week or two (depending how fast my thing goes).

**Comment by aleksip** [comment]
Thanks for again replying so quickly! No worries, I wrote these down just as much for myself, since I will have to stop working on on my site for a while. I hope I can find some time to contribute to the project at some point.

**Comment by swentel** [comment]
So there were quite some problems indeed with views :)

But they were relatively easy to fix. Added in this commit (and available on dev on d.o)

- filter validation fix (for both property and type)
- summary for those filters in views
- added 'Webmention current path' default argument plugin which you can use on the 'target' field in the contextual filters
- added a 'Webmention template' row plugin which uses the template file, along with some options.

I also added new options to the existing Webmentions block: 

- show mentions, bookmarks
- sort by field (id, created, changed)
- sort direction (asc, desc)

So you can actually choose now :)

**Comment by aleksip** [comment]
Wow, will try these ASAP!
