### ISSUE TITLE
Error sending webmention for a comment reply

### ISSUE THREAD

**Issue by aleksip** [swentel/indieweb#426]
I'm trying to reply on my site to a comment that has been created from a webmention and am getting the following error when trying to publish a webmention for the reply:

<code>Error sending webmention for https://www.aleksip.net/comment/indieweb/359 to https://brid.gy/publish/twitter: Client error: `POST https://brid.gy/publish/webmention` resulted in a `400 Bad Request` response: { "parsed": { "rels": { "me": [ "https://twitter.com/aleksip", "https://github.com/aleksip" (truncated...) </code>

**Comment by swentel** [comment]
Hmm, that rather feels like a bug at bridgy. I think, but I'm not sure, that bridgy has logs, can you see that in the interface somewhere? If not, then I'll ping the maintainer of bridgy.

**Comment by aleksip** [comment]
Ah, yes: `2019-10-02 07:29:55.558914 I No microformats2 data found in https://www.aleksip.net/comment/indieweb/359`.

**Comment by swentel** [comment]
Ok, you wil probably need to to configure the micoformat view mode for comments. If it's not available, you can always create it. The machine name has to be 'indieweb_microformat'.

**Comment by aleksip** [comment]
Yes, that was it, thanks!

I'll have to tweak the contents of the view mode a bit it seems, but I also noticed that the reply does not show up as a reply to the original tweet in Twitter. Is this due to misconfiguration on my site, or a bug in either IndieWeb or Bridgy, or is it simply impossible to do?

**Comment by swentel** [comment]
It is possible yes. Mine usually end up on the right place. You should have a 'publish' fieldset on a comment where you need to:

- toggle 'publish to twitter' in case it needs to go back to twitter
- fill in a reply field: the comment needs a link field where you fill in the url you are replying to, in this case that's going to be the twitter status url.

**Comment by aleksip** [comment]
Do you still add the Twitter @handle in the beginning or is that done by Bridgy or Twitter?

**Comment by swentel** [comment]
I don't add it. If the target url is a specific url, it will work.

**Comment by swentel** [comment]
Example on my site:

https://twitter.com/wimleers/status/1152248858627497986 : this is a reply on twitter from wim on a post which originally came from by site.

I then replied from my site: this is the canonical indieweb url for the comment that bridgy can parse: https://realize.be/comment/indieweb/4532

Full thread is at https://realize.be/notes/1890

**Comment by aleksip** [comment]
Thanks, that clarified things a lot! I have been adding the Twitter status URL I want to reply to in the 'Enter a custom URL' field in the 'Publish to' section of the comment form.

**Comment by aleksip** [comment]
How do you add the 'In reply to' link to the indieweb_microformat display?

**Comment by aleksip** [comment]
You have just added an extra comment field for this use?

**Comment by swentel** [comment]
Yeah, I can imagine it's confusing. It took me a while as well to wrap my head around :)

Add a custom url field on the comment type - See the manage fields on my site:
![comment-fields](https://user-images.githubusercontent.com/168466/66044938-939d9800-e51a-11e9-8838-b63ac28fa1df.png)

Use the in-reply-to microformat then on manage display.

If you then create a reply, enter the url of the target in that field and then

- publish to twitter? -> toggle to publish to twitter in the publish section, that's it
- my site for instance -> select either the 'link field' or enter it again in the custom url

**Comment by aleksip** [comment]
Finally have everything working, after discovering that I also need to use the 'Microformat link' field formatter for the reply field. 😊 🎉

Thank you so much for all your help! Not sure if some or all of this was documented somewhere. If it was, I'm sorry I missed it. If not, this issue should hopefully pass as documentation of some kind!

**Comment by swentel** [comment]
There's some minimal information on admin/config/services/indieweb/send page in the "Custom URL's for content" section, but it's easily overlooked I guess :)

**Comment by aleksip** [comment]
I have kept reading the help texts on that and the other IndieWeb admin pages again and again, but for someone new to all this (or maybe just me) they are completely undecipherable at first, and only slowly start to make perfect sense! This is to say there is absolutely nothing wrong with the help texts themselves. 😄

**Comment by swentel** [comment]
> they are completely undecipherable at first

Don't worry. My head exploded when reading through all the specs in the IndieWeb world and all the integrations. I'm glad I do have something minimal on the UI and in the README, that also contains some information about this - and many other things.

I just hope everything more or less makes sense. English is also not my mother tongue, so sometimes it might sound a little funky :)
