### ISSUE TITLE
Layout Builder and the Twitter (bridgy) field

### ISSUE THREAD

**Issue by aleksip** [swentel/indieweb#433]
When using the Twitter (bridgy) field as a Layout Builder block, the Bridgy link does not seem to appear in the HTML.

**Comment by swentel** [comment]
Hmm interesting. As far as I know, this should work out of the box with core, but I'll have to double check.

**Comment by swentel** [comment]
Double checked, works fine here. Enabled layout builder and I see in the source, see screenshot.

![layout-builder-extra-fields](https://user-images.githubusercontent.com/168466/67391947-f5907100-f59f-11e9-9cc4-c47e9e827ac9.png)

**Comment by aleksip** [comment]
Thanks for checking and very sorry for your trouble, must be something to do with my site setup then. Closing this now, but will add a comment here when I find out the real problem!

**Comment by swentel** [comment]
If it's a bug, then it might be core, or the way it handles extra fields, not sure. I just enabled layout builder on the content type and the fields which were already in the manage display where nicely imported into the default layout. I haven't done any manual intervention here.
