### ISSUE TITLE
Like escaping is not supported in the way it is used

### ISSUE THREAD

**Issue by alexpott** [swentel/indieweb#455]
I'm reading through https://www.drupal.org/project/drupal/issues/2786811 and discovered that one of the indieweb module is affected.
```
  public function checkIdenticalSyndication($like) {
    return $this->database->query("SELECT count(url) as count FROM {webmention_syndication} WHERE url LIKE :match_url", [':match_url' => '%/' . Database::getConnection()->escapeLike($like)])->fetchField();
  }
```

For cross db support this needs to use a query builder.

**Comment by swentel** [comment]
Well, developers can swap the storage class if they want to make it work on another db backend :)

Joke aside, fixed, thanks for letting me know!
