### ISSUE TITLE
Logo for the project and Drupal.org project page.

### ISSUE THREAD

**Issue by Grienauer** [swentel/indieweb#460]
I propose a logo for the indieweb Drupal Module.
I think it deserves one :)
Here is my proposals:

https://ibb.co/F61wSWG

here are the official indiewebcamp logos https://indieweb.org/logo
I already spoke to Shane Becker wo did a "3d" proposal for an indieweb logo (he is fine to modify his version and his is public domain. I recreated it from scratch and added the "druplicon part".

I created the logos for Paragraphs, Rules, GraphQL, Bricks, Omega (4!), Coffee, Shariff, fluxkraft, Debunk CMS, OpenTrigger, WebApp Module…

If you like it, I could make a final version, so you can add it to the project page :)

with kind regards from Vienna,
Grienauer

**Comment by swentel** [comment]
Cool!

My personal preference is the first one with the blue color as that clearly is a reference to Drupal of course.

Reading https://www.drupal.org/about/media-kit/logos it looks like it's probably ok - although I have no idea about those legal stuff :)

(note: I do like the orange as well, as it matches the IndieWeb colors)

**Comment by Grienauer** [comment]
yellow version: https://ibb.co/TbnzkK9
blue version: https://ibb.co/ngKVJy8
new yellow version with gradient to symbolize the Drupal part and keep the indiewebcamp colors too: https://ibb.co/W0L12Xz
If you need another version, please let me know…
Happy for a mention to add it over at my profile https://www.drupal.org/u/grienauer :P

**Comment by swentel** [comment]
Done, Thanks!
