### ISSUE TITLE
Auto reply not working for non twitter urls?

### ISSUE THREAD

**Issue by swentel** [swentel/indieweb#522]
see https://realize.be/comment/indieweb/5024

**Comment by sparxsys** [comment]
I was playing with it today and thought of sharing few more details.

When I reply to a comment that I received on my site from twitter, I get the following error in the Drupal log.

Error sending webmention for https://www.ravisagar.in/comment/indieweb/13633 to https://brid.gy/publish/twitter: Client error: `POST https://brid.gy/publish/webmention` resulted in a `400 Bad Request` response: { "error": "Couldn't find link to brid.gy/publish/twitter" }

Then I added a comment_target_link field in my comment and also selected it in the configuration. Made sure the formatting is correct in the manage display (admin/config/services/indieweb/send), and when replying to the comment I manually populated the twitter link (from where I received the comment) and ran the cron. I received the same error.

Thanks

**Comment by swentel** [comment]
That's because the 'Syndication' isn't in the manage display (exists both for comment and nodes).

**Comment by swentel** [comment]
Sorry, there should be a 'Twitter' field (which prints the brid.gy link), that one needs to be in manage display.

**Comment by sparxsys** [comment]
I added the syndication field in the comment and it added a reply on twitter when I manually entered the twitter link in the comment target link.

This is how my comment form looks like.
![Screenshot 2020-09-02 at 14 35 22](https://user-images.githubusercontent.com/2854039/91990442-9f489e80-ed29-11ea-9416-1251d52e68ca.png)

Is there a way the comment target link get automatically populated with the previous comment's twitter link? In the comment's webmention info I can see that twitter url. Without comment target link the tweet is sent by not added as a reply to existing thread.

**Comment by sparxsys** [comment]
I think I got it now. I was doing this from the Drupal UI. When I used Indigenous app and replied to the comment (with twitter (bridgy) checked) then it indeed populated the comment target link. Thanks for the clarification. I am getting there. I am now trying to setup Fediverse. Also faced some issues but I posted in their project.

**Comment by swentel** [comment]
Tried it myself again and my queue was filled, so that conversion of those admin/content/webmention url's does work.
